### ISSUE TITLE
[Critical] execute_command returns the wrong result 

### ISSUE THREAD

**Issue by duke-cliff** [Grokzen/redis-py-cluster#401]
We have a working application with standalone redis mode + replicas. However, we are hitting AWS limit(5 replicas maxed out) and we need more CPU power, that's why we are investigating to migrate to the cluster-mode.

Our main business logic will read a list of keys from redis, the result should be either a `json str` or `nil`.

Today I enabled a partial load to read from redis-cluster with `read_from_replicas=True` using your library, but I received some responses completely are not making any sense:

```
[
b'OK',   <========== I didn't read all the errors but seems like the OK always happens in the head of the return.
None, 
b'{".....a json str....}'
]
```

I also received many errors of this:
![image](https://user-images.githubusercontent.com/5668429/94883388-90dcc800-0438-11eb-8784-e9d68fd34e43.png)

**Comment by duke-cliff** [comment]
I am using v2.0.0. Not sure if this might be some problems already are solved?

**Comment by duke-cliff** [comment]
Also `READONLY` does not need to be executed before every command. You can just call it once when the connection is initialized like what redis-go does: https://github.com/go-redis/redis/blob/7125bf611e5d7d9bb4487dd6cb80d888bad92d23/redis.go#L272

**Comment by duke-cliff** [comment]
I think I know why the redis-py version we use (2.0.0) does not support `readonly` command yet. I will upgrade our libraries and retry next week.

**Comment by Grokzen** [comment]
If you look into the on_connect method in ClusterConnection class then you see that we should send up a `READONLY` command each time the connection is created instead of the need to have it in the execute_command section.

I am interested tho in what exception got from the parse_response section tho?

Also yes please do try 2.1.0 to see if there is any difference in there. It might be some fixes in there for this problem.

**Comment by duke-cliff** [comment]
The exception is `self.parse_response(r, 'READONLY',...)` has nothing `None` in the return. It supposes to get `OK`.
After digging into the redis-py code, I found the version 3.0.0 we use does not even have this command in this dictionary: https://github.com/go-redis/redis/blob/eb28cb64264d03218e5aa8f35eb66a4e4c4ba60b/cluster.go#L1124

I think the `wrong OK reponse` in mget is also due to this, because the previous `READONLY`response was not read. And later `mget` which is `get` will read the previous response from `readonly` as string.

I have done some tests locally today with latest redis-py and py-cluster 2.1.0, the problem should be fixed.



But still, you are adding one extra `READONLY` cmd before every other read command. This is a waste and should be `only set once` on slave connections.

**Comment by Grokzen** [comment]
@duke-cliff I will close this issue with the solution that 2.1.0 solves the problem. Yes we still have the open PR:s that we need to merge but anyone else getting to this just upgrade to 2.1.0 release and it should be resolved. More fixes will be added in to 2.1.1 later when the PR:s is done.
